version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: node0
  coins:
  - 100000000utlore
- name: node1
  coins:
  - 100000000utlore
  address: gitopia1rrad3vleav3svu7tutqp9sqqv9mh4gex62vjvm
- name: node2
  coins:
  - 100000000utlore
  address: gitopia1s9qkkznqqv8p838fuyzzfaxu7ckhy3v8cw3pke
- name: node3
  coins:
  - 50000000utlore
  address: gitopia1gqacec5zhz6js5nlwfmsfcx8qkghf0y5na4q5a
- name: faucet
  coins:
  - 100000000utlore
faucet:
  name: faucet
  coins:
  - 1000000utlore
  coins_max:
  - 3000000utlore
  host: 0.0.0.0:4500
  port: 4500
client:
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    bank:
      denom_metadata:
      - base: utlore
        denom_units:
        - denom: utlore
          exponent: 0
        - denom: tlore
          exponent: 6
        description: The native staking token of the Gitopia Hub.
        display: tlore
        name: tlore
        symbol: tlore
    crisis:
      constant_fee:
        denom: utlore
    gov:
      deposit_params:
        max_deposit_period: 60s
        min_deposit:
        - amount: "10000000"
          denom: utlore
      voting_params:
        voting_period: 60s
    mint:
      params:
        mint_denom: utlore
    staking:
      params:
        bond_denom: utlore
    distribution:
      params:
        community_tax: "0"
    gitopia:
      params:
        next_inflation_time: "2024-12-28T05:33:18.234521Z"
        distribution_proportions:
        - address: gitopia1rrad3vleav3svu7tutqp9sqqv9mh4gex62vjvm # ecosystem
          proportion: 40
        - address: gitopia1rrad3vleav3svu7tutqp9sqqv9mh4gex62vjvm # team
          proportion: 25
        - address: gitopia1rrad3vleav3svu7tutqp9sqqv9mh4gex62vjvm # community
          proportion: 5
validators:
- name: node0
  bonded: 100000000utlore
