version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: node0
  coins:
  - 200000000ulore
- name: node1
  coins:
  - 100000000ulore
  address: gitopia1rrad3vleav3svu7tutqp9sqqv9mh4gex62vjvm
- name: node2
  coins:
  - 100000000ulore
  address: gitopia1s9qkkznqqv8p838fuyzzfaxu7ckhy3v8cw3pke
- name: node3
  coins:
  - 50000000ulore
  address: gitopia1gqacec5zhz6js5nlwfmsfcx8qkghf0y5na4q5a
- name: faucet
  coins:
  - 100000000utlore
- name: evaluator
  coins:
  - 100000000utlore
  address: gitopia1tfsvwp95023a64rnke7vxd3jjlp5fg4m46yx9j
faucet:
  name: faucet
  coins:
  - 1000000ulore
  coins_max:
  - 3000000ulore
  host: 0.0.0.0:4500
  port: 4500
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    bank:
      denom_metadata:
      - base: ulore
        denom_units:
        - denom: ulore
          exponent: 0
        - denom: lore
          exponent: 6
        description: The native staking token of the Gitopia Hub.
        display: lore
        name: lore
        symbol: lore
    crisis:
      constant_fee:
        denom: ulore
    distribution:
      params:
        community_tax: "0"
    gitopia:
      params:
        distribution_proportions:
        - address: gitopia1rrad3vleav3svu7tutqp9sqqv9mh4gex62vjvm
          proportion: 40
        - address: gitopia1rrad3vleav3svu7tutqp9sqqv9mh4gex62vjvm
          proportion: 25
        - address: gitopia1rrad3vleav3svu7tutqp9sqqv9mh4gex62vjvm
          proportion: 5
        next_inflation_time: "2024-12-28T05:33:18.234521Z"
    rewards: 
      params:
        evaluator_address: gitopia1tfsvwp95023a64rnke7vxd3jjlp5fg4m46yx9j
        reward_series:
          series_one: 
            total_amount: 
              amount: "2000000"
              denom: "utlore"
          series_two: 
            total_amount: 
              amount: "1700000"
              denom: "utlore"
          series_three: 
            total_amount: 
              amount: "1400000"
              denom: "utlore"
          series_four: 
            total_amount: 
              amount: "1100000"
              denom: "utlore"
          series_five: 
            total_amount: 
              amount: "800000"
              denom: "utlore"
          series_six: 
            total_amount: 
              amount: "500000"
              denom: "utlore"
          series_seven: 
            total_amount: 
              amount: "250000"
              denom: "utlore"
    gov:
      deposit_params:
        max_deposit_period: 60s
        min_deposit:
        - amount: "10000000"
          denom: ulore
      voting_params:
        voting_period: 60s
    mint:
      params:
        mint_denom: ulore
    staking:
      params:
        bond_denom: ulore
validators:
- name: node0
  bonded: 100000000ulore
