genesis:
  app_state:
    staking:
      params:
        bond_denom: "tlore"
    gov:
      deposit_params:
        max_deposit_period: "60s"
        min_deposit: [{ "amount": "10000000", "denom": "tlore" }]
      voting_params:
        voting_period: "60s"
    mint:
      params:
        mint_denom: "tlore"
    crisis:
      constant_fee:
        denom: "tlore"
accounts:
  - name: node0
    coins: ["100000000tlore"]
  - name: node1
    coins: ["100000000tlore"]
  - name: node2
    coins: ["100000000tlore"]
  - name: node3
    coins: ["50000000tlore"]
  - name: faucet
    coins: ["100000000tlore"]
validator:
  name: node0
  staked: "100000000tlore"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: faucet
  coins: ["5tlore"]
  coins_max: ["15tlore"]
  port: 4500
