genesis:
  app_state:
    staking:
      params:
        bond_denom: "utlore"
    gov:
      deposit_params:
        max_deposit_period: "60s"
        min_deposit: [{ "amount": "10000000", "denom": "utlore" }]
      voting_params:
        voting_period: "60s"
    mint:
      params:
        mint_denom: "utlore"
    crisis:
      constant_fee:
        denom: "utlore"
    bank:
      denom_metadata:
        - description: "The native staking token of the Gitopia Hub."
          denom_units:
            - denom: "utlore"
              exponent: 0
            - denom: "tlore"
              exponent: 6
          base: "utlore"
          display: "tlore"
          name: "tlore"
          symbol: "tlore"
accounts:
  - name: node0
    coins: ["100000000utlore"]
  - name: node1
    coins: ["100000000utlore"]
  - name: node2
    coins: ["100000000utlore"]
  - name: node3
    coins: ["50000000utlore"]
  - name: faucet
    coins: ["100000000utlore"]
validator:
  name: node0
  staked: "100000000utlore"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: faucet
  coins: ["1000000utlore"]
  coins_max: ["3000000utlore"]
  port: 4500
